language: node_js
node_js:
  - '8'

script:
  - yarn test --coverage && cat ./coverage/lcov.info | npx coveralls && rm -rf ./coverage
  - yarn lib

cache:
  yarn: true
  directories:
    - node_modules
